//
//  DetailsPresenter.swift
//  ott
//
//  Created by dpsmac1 on 25-04-18.
//  Copyright (c) 2018 Digitalproserver. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class DetailsPresenter {
    
    // MARK: - Public properties -
    private var _initialMedia: Media {
        didSet {
            _interactor.fetchDetails(media: _initialMedia)
        }
    }
    var media: Media?
    
    // MARK: - Private properties -

    private unowned var _view: DetailsViewInterface
    private var _interactor: DetailsInteractorInterface
    private var _wireframe: DetailsWireframeInterface

    // MARK: - Lifecycle -

    init(wireframe: DetailsWireframeInterface, view: DetailsViewInterface, interactor: DetailsInteractorInterface, media: Media) {
        _wireframe = wireframe
        _view = view
        _interactor = interactor
        _initialMedia = media
    }
    
    func viewDidLoad() {
        _interactor.fetchDetails(media: _initialMedia)
    }
}

// MARK: - Extensions -

extension DetailsPresenter: DetailsPresenterInterface {
    func showSideMenu() {
        _view.showSideMenu()
    }
    
    func closePopup() {
        _wireframe.navigate(to: .closePopup)
    }
}




// MARK: - Web service
extension DetailsPresenter {
    func fetchDetails(_ media: Media) {
        _view.showLoadingIndicator()
        _interactor.fetchDetails(media: media)
    }
    
    func successFetchingDetails(_ media: Media) {
        _view.hideLoadingIndicator()
        print("SUCCESS: \(media)")
    }
    
    func failureFetchingDetails(_ error: Error?) {
        _view.hideLoadingIndicator()
        print("FAILURE: \(error)")
    }
}
