//
//  DetailsInteractor.swift
//  ott
//
//  Created by dpsmac1 on 25-04-18.
//  Copyright (c) 2018 Digitalproserver. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import Alamofire

final class DetailsInteractor {
    weak var presenter: DetailsPresenter!
}

// MARK: - Extensions -

extension DetailsInteractor: DetailsInteractorInterface {
    func fetchDetails(media: Media) {
        let params: Parameters = [
            "user_token": Constants.API.userToken,
            "media": media.slug
        ]
        
        ApiClient.post("medias/details.php", params: params, success: { response in
            do {
                print("RESPONSE: \(response)")
                let mediaDetails = try JSONDecoder().decode(MediaDetailsNode.self, from: response)
                self.presenter.successFetchingDetails(mediaDetails.media)
            } catch {
                self.presenter.failureFetchingDetails(error)
            }
        }) { error in
            print("[HomeInteractor] ERROR: \(String(describing: error))")
            self.presenter.failureFetchingDetails(error)
        }
    }
}




// MARK: - Response Models
extension DetailsInteractor {
    struct MediaDetailsNode: Decodable {
        enum CodingKeys: String, CodingKey { case media }
        let media: Media
    }
}
