//
//  DetailsWireframe.swift
//  ott
//
//  Created by dpsmac1 on 25-04-18.
//  Copyright (c) 2018 Digitalproserver. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class DetailsWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let _storyboard = UIStoryboard(name: "Details", bundle: nil)

    // MARK: - Module setup -

    init(_ media: Media) {
        let moduleViewController = _storyboard.instantiateViewController(ofType: DetailsViewController.self)
        let navigationController = DetailsNavigationController(rootViewController: moduleViewController)        
        super.init(viewController: navigationController)

        let interactor = DetailsInteractor()
        let presenter = DetailsPresenter(wireframe: self, view: moduleViewController, interactor: interactor, media: media)
        interactor.presenter = presenter
        moduleViewController.presenter = presenter
    }

}




// MARK: - Extensions -
extension DetailsWireframe: DetailsWireframeInterface {

    func navigate(to option: DetailsNavigationOption) {
        switch option {
        case .closePopup:
            viewController.dismiss(animated: true, completion: nil)
        }
    }
}
