//
//  HomeInterfaces.swift
//  ott
//
//  Created by dpsmac1 on 24-04-18.
//  Copyright (c) 2018 Digitalproserver. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum HomeNavigationOption {
    case details(Media)
}


protocol HomeWireframeInterface: WireframeInterface {
    func navigate(to option: HomeNavigationOption)
}

protocol HomeViewInterface: ViewInterface {
    var categories: [Category]? { get set }
    var highlights: [Media]? { get set }
    
    func showLoadingIndicator()
    func hideLoadingIndicator()
}

protocol HomePresenterInterface: PresenterInterface, HomePagerSlideDelegate {
    func showSideMenu()
    
    func fetchCategories()
    func successFetchingCategories(_ categories: [Category])
    func failureFetchingCategories(_ error: Error?)
    
    func fetchHighlights()
    func successFetchingHighlights(_ highlights: [Media])
    func failureFetchingHighlights(_ error: Error?)
    
    func goToDetails(media: Media)
    func didSelectHighlight(_ highlight: Media)
}

protocol HomeInteractorInterface: InteractorInterface {
    func fetchCategories()
    func fetchHighlights()
}
